package ISP;
import com.mysql.jdbc.Driver;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.mysql.jdbc.Driver;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date; 
import java.text.DateFormat; 
import java.text.SimpleDateFormat; 
/*
 - Purwanto         2210141039
 - Florensius Ghesa 2210141055
 2 D4 TK B
*/
public class Utama extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    Connection paketKonek;
    //objek deklarasi
    static Utama gui = new Utama();
    static Testimoni testimoni = new Testimoni();
    static praBayar pra = new praBayar();
    static pascaBayar pasca = new pascaBayar();
    static Admin admin = new Admin();
    static Browser browser = new Browser();
    //end objek deklarasi
    private boolean adminLogin=false,praLogin=false,pascaLogin=false;
    private String Testimoni=" => silahkan isi testimoni <= ";
    private int currentPaket,buttonKonfirmasi,step;
    /**
     * Creates new form Utama
     */
    public Utama() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tanyaDaftar = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pascaTab = new javax.swing.JPanel();
        pascaNamaField = new javax.swing.JTextField();
        emailNamaField = new javax.swing.JTextField();
        notelpNamaField = new javax.swing.JTextField();
        passNamaField = new javax.swing.JTextField();
        labelPeriintah = new javax.swing.JLabel();
        pascaCekDaftar = new javax.swing.JCheckBox();
        pascaDaftarButton = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        labelTelp = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelPass = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        praTab = new javax.swing.JPanel();
        tanyaDaftarPra = new javax.swing.JLabel();
        kodeCopyField = new javax.swing.JTextField();
        generateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        simpanBaik2 = new javax.swing.JCheckBox();
        praDaftarButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        adminTab = new javax.swing.JPanel();
        adminKodeField = new javax.swing.JTextField();
        adminLogInButton = new javax.swing.JButton();
        adminLabel = new javax.swing.JLabel();
        adminPasswordField = new javax.swing.JTextField();
        ubahPass = new javax.swing.JTextField();
        konfirmasiUbah = new javax.swing.JTextField();
        adminLogInButton1 = new javax.swing.JButton();
        konfirmasiAdmin = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        adminLabel2 = new javax.swing.JLabel();
        ubahKode = new javax.swing.JTextField();
        tanyaAdmin = new javax.swing.JLabel();
        adminCombo = new javax.swing.JComboBox();
        paketTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paketBu = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPaket = new javax.swing.JTable();
        labelInformasi = new javax.swing.JLabel();
        pilihanTentang = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        LCDBantuan = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        tanyaLogin = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        pascaLogInButton = new javax.swing.JButton();
        passField = new javax.swing.JTextField();
        ketISP = new javax.swing.JLabel();
        ISP = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LCDUtama = new javax.swing.JTextPane();
        beliButton = new javax.swing.JButton();
        comboPaket = new javax.swing.JComboBox();
        tanyaPaket = new javax.swing.JLabel();
        pascaDataDiri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jamLabel = new javax.swing.JLabel();
        updateJam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("@warkop.id");
        setBackground(new java.awt.Color(0, 0, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tanyaDaftar.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        tanyaDaftar.setText("Belum Punya Akun? Daftar Disini");

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N

        pascaTab.setBackground(new java.awt.Color(204, 255, 255));
        pascaTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pascaNamaField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        pascaNamaField.setText("nama");

        emailNamaField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        emailNamaField.setText("email");

        notelpNamaField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        notelpNamaField.setText("no telp");

        passNamaField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        passNamaField.setText("password");

        labelPeriintah.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        labelPeriintah.setText("masukkan data berikut dengan benar");

        pascaCekDaftar.setBackground(new java.awt.Color(204, 255, 255));
        pascaCekDaftar.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        pascaCekDaftar.setText("setuju untuk gabung");
        pascaCekDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pascaCekDaftarActionPerformed(evt);
            }
        });

        pascaDaftarButton.setBackground(new java.awt.Color(255, 255, 255));
        pascaDaftarButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        pascaDaftarButton.setText("Daftar");
        pascaDaftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pascaDaftarButtonActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        labelNama.setText("nama");

        labelTelp.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        labelTelp.setText("no telp");

        labelEmail.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        labelEmail.setText("email");

        labelPass.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        labelPass.setText("password");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/wifiIcon2.png"))); // NOI18N
        jLabel8.setText("jLabel3");

        javax.swing.GroupLayout pascaTabLayout = new javax.swing.GroupLayout(pascaTab);
        pascaTab.setLayout(pascaTabLayout);
        pascaTabLayout.setHorizontalGroup(
            pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pascaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pascaTabLayout.createSequentialGroup()
                        .addComponent(labelPeriintah)
                        .addContainerGap(135, Short.MAX_VALUE))
                    .addGroup(pascaTabLayout.createSequentialGroup()
                        .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNama)
                            .addComponent(labelTelp)
                            .addComponent(labelEmail)
                            .addComponent(labelPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(notelpNamaField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailNamaField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passNamaField, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(pascaNamaField))
                        .addGap(18, 18, 18)
                        .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pascaTabLayout.createSequentialGroup()
                                .addComponent(pascaCekDaftar)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pascaTabLayout.createSequentialGroup()
                                .addComponent(pascaDaftarButton)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pascaTabLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))))
        );

        pascaTabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pascaCekDaftar, pascaDaftarButton});

        pascaTabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelEmail, labelNama, labelPass, labelTelp});

        pascaTabLayout.setVerticalGroup(
            pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pascaTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPeriintah)
                .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pascaTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pascaNamaField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notelpNamaField))
                        .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pascaTabLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pascaTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailNamaField)
                                    .addComponent(pascaCekDaftar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPass, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pascaTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(passNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pascaDaftarButton)))
                        .addGap(57, 57, 57))
                    .addGroup(pascaTabLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pascaTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailNamaField, notelpNamaField, pascaNamaField, passNamaField});

        pascaTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pascaCekDaftar, pascaDaftarButton});

        jTabbedPane2.addTab("Pasca Bayar", pascaTab);

        praTab.setBackground(new java.awt.Color(204, 255, 255));
        praTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tanyaDaftarPra.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        tanyaDaftarPra.setText("klik generate kode untuk memulai");

        kodeCopyField.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        kodeCopyField.setText("kode");
        kodeCopyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeCopyFieldActionPerformed(evt);
            }
        });

        generateButton.setBackground(new java.awt.Color(255, 255, 255));
        generateButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        generateButton.setText("Generate");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jLabel4.setText("harap untuk simpan kode baik-baik");

        simpanBaik2.setBackground(new java.awt.Color(204, 255, 255));
        simpanBaik2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        simpanBaik2.setText("setuju untuk gabung");
        simpanBaik2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                simpanBaik2StateChanged(evt);
            }
        });
        simpanBaik2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBaik2ActionPerformed(evt);
            }
        });

        praDaftarButton.setBackground(new java.awt.Color(255, 255, 255));
        praDaftarButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        praDaftarButton.setText("Daftar");
        praDaftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                praDaftarButtonActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/wifiIcon2.png"))); // NOI18N
        jLabel6.setText("jLabel3");

        javax.swing.GroupLayout praTabLayout = new javax.swing.GroupLayout(praTab);
        praTab.setLayout(praTabLayout);
        praTabLayout.setHorizontalGroup(
            praTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(praTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(praTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanyaDaftarPra)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, praTabLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addGroup(praTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, praTabLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(praTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(praDaftarButton)
                    .addComponent(simpanBaik2)
                    .addComponent(kodeCopyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        praTabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {generateButton, kodeCopyField});

        praTabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {praDaftarButton, simpanBaik2});

        praTabLayout.setVerticalGroup(
            praTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(praTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tanyaDaftarPra)
                .addGap(36, 36, 36)
                .addGroup(praTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeCopyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(praTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(praTabLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(simpanBaik2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(praDaftarButton))
                    .addGroup(praTabLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        praTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {generateButton, kodeCopyField});

        praTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {praDaftarButton, simpanBaik2});

        jTabbedPane2.addTab("Pra Bayar", praTab);

        adminTab.setBackground(new java.awt.Color(204, 255, 255));
        adminTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        adminKodeField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        adminKodeField.setText("kode");

        adminLogInButton.setBackground(new java.awt.Color(255, 255, 255));
        adminLogInButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        adminLogInButton.setText("Log In");
        adminLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInButtonActionPerformed(evt);
            }
        });

        adminLabel.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        adminLabel.setText("log in");

        adminPasswordField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        adminPasswordField.setText("password");

        ubahPass.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        ubahPass.setText("password");

        konfirmasiUbah.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        konfirmasiUbah.setText("konfirm password");

        adminLogInButton1.setBackground(new java.awt.Color(255, 255, 255));
        adminLogInButton1.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        adminLogInButton1.setText("ubah");
        adminLogInButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogInButton1ActionPerformed(evt);
            }
        });

        konfirmasiAdmin.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        konfirmasiAdmin.setForeground(new java.awt.Color(255, 0, 0));
        konfirmasiAdmin.setText("! belum log in");

        jCheckBox3.setBackground(new java.awt.Color(204, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jCheckBox3.setText("ubah akun");

        adminLabel2.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        adminLabel2.setText("ubah akun");

        ubahKode.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        ubahKode.setText("kode");

        tanyaAdmin.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        tanyaAdmin.setText(" ");

        adminCombo.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        adminCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "lihat pra bayar", "lihat pasca bayar", "lihat list transaksi" }));
        adminCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminTabLayout = new javax.swing.GroupLayout(adminTab);
        adminTab.setLayout(adminTabLayout);
        adminTabLayout.setHorizontalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(adminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(adminLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(adminPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(adminKodeField)
                            .addComponent(tanyaAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(adminCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminTabLayout.createSequentialGroup()
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ubahPass, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(ubahKode)
                            .addComponent(konfirmasiUbah))
                        .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminTabLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminTabLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adminLogInButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(konfirmasiAdmin))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminTabLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {konfirmasiUbah, ubahKode, ubahPass});

        adminTabLayout.setVerticalGroup(
            adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminKodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLogInButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanyaAdmin)
                    .addComponent(adminCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahKode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLabel2)
                    .addComponent(konfirmasiAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubahPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(konfirmasiUbah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLogInButton1))
                .addContainerGap())
        );

        adminTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adminKodeField, adminLabel, adminLogInButton, adminPasswordField, tanyaAdmin});

        adminTabLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {adminLabel2, adminLogInButton1, jCheckBox3, konfirmasiAdmin, konfirmasiUbah, ubahKode, ubahPass});

        jTabbedPane2.addTab("Admin", adminTab);

        paketTab.setBackground(new java.awt.Color(204, 255, 255));
        paketTab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 12)); // NOI18N
        jLabel1.setText("paket kami yang bisa dinikmati setiap saat");

        paketBu.setText("tampilkan");
        paketBu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketBuActionPerformed(evt);
            }
        });

        tabelPaket.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        tabelPaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "", null, null, null, null},
                {"2", null, null, null, null, null},
                {"3", null, null, null, null, null},
                {"4", null, null, null, null, null}
            },
            new String [] {
                "No", "Nama", "Quota", "Kecepatan", "Masa Aktif", "Harga"
            }
        ));
        tabelPaket.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tabelPaket);
        tabelPaket.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout paketTabLayout = new javax.swing.GroupLayout(paketTab);
        paketTab.setLayout(paketTabLayout);
        paketTabLayout.setHorizontalGroup(
            paketTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketTabLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(paketTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paketTabLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paketTabLayout.createSequentialGroup()
                        .addComponent(paketBu)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paketTabLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        paketTabLayout.setVerticalGroup(
            paketTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketTabLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(paketBu)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Paket Kami", paketTab);

        labelInformasi.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        labelInformasi.setText("butuh informasi? ada disini");

        pilihanTentang.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        pilihanTentang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bantuan", "aplikasi apa ini", "Tentang Kami", "Testimoni", " " }));
        pilihanTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanTentangActionPerformed(evt);
            }
        });

        LCDBantuan.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(LCDBantuan);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tanyaLogin.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        tanyaLogin.setText("Sudah Punya Akun?");

        emailField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        emailField.setText("email");

        pascaLogInButton.setBackground(new java.awt.Color(255, 255, 255));
        pascaLogInButton.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        pascaLogInButton.setText("Log In");
        pascaLogInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pascaLogInButtonActionPerformed(evt);
            }
        });

        passField.setFont(new java.awt.Font("Aharoni", 0, 14)); // NOI18N
        passField.setText("password");

        ketISP.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        ketISP.setText("selamat datang internet cepat dan mudah");

        ISP.setFont(new java.awt.Font("Aharoni", 1, 53)); // NOI18N
        ISP.setText("@warkop.id");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/wifiIcon.png"))); // NOI18N
        jLabel5.setText(" ");

        jLabel7.setText(" ");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/wifiIcon2.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ISP, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(ketISP))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pascaLogInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tanyaLogin)
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ISP, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ketISP))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(tanyaLogin))
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pascaLogInButton)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailField, pascaLogInButton, passField});

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LCDUtama.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(LCDUtama);

        beliButton.setBackground(new java.awt.Color(255, 255, 255));
        beliButton.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        beliButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/beli.png"))); // NOI18N
        beliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliButtonActionPerformed(evt);
            }
        });

        comboPaket.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        comboPaket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paket 1", "Paket 2", "Paket 3", "Paket 4", "Paket 5", "Paket 6", "Paket 7", "Paket 8", "Paket 9", "Paket 10", "Paket 11", "Paket 12", "Paket 13", "Paket 14", "Paket 15", "Paket 16", "Paket 17", "Paket 18", "Paket 19", "Paket 20" }));
        comboPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaketActionPerformed(evt);
            }
        });

        tanyaPaket.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        tanyaPaket.setText("pilih paket");

        pascaDataDiri.setBackground(new java.awt.Color(255, 255, 255));
        pascaDataDiri.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        pascaDataDiri.setText("lihat data diri");
        pascaDataDiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pascaDataDiriActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jLabel2.setText("atau");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logout.png"))); // NOI18N
        jButton1.setText("log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanyaPaket, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(pascaDataDiri, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(comboPaket, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(beliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboPaket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanyaPaket))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(pascaDataDiri))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(beliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboPaket, jLabel2, tanyaPaket});

        jamLabel.setFont(new java.awt.Font("Aharoni", 1, 18)); // NOI18N
        jamLabel.setText("klik update");

        updateJam.setBackground(new java.awt.Color(255, 255, 255));
        updateJam.setFont(new java.awt.Font("Aharoni", 1, 14)); // NOI18N
        updateJam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/clock.png"))); // NOI18N
        updateJam.setText("update");
        updateJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tanyaDaftar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(labelInformasi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(pilihanTentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateJam, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanyaDaftar)
                            .addComponent(jamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateJam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelInformasi)
                            .addComponent(pilihanTentang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void getKonekPaket() throws SQLException{
        try{
            String id, pass, driver, url;
            id = "root";
            pass = "";
            driver = "com.mysql.jdbc.Driver";
            url = "jdbc:mysql://localhost:3306/coba";
            Class.forName(driver).newInstance();
            paketKonek = DriverManager.getConnection(url,id,pass);
            if (paketKonek==null){
                System.out.println("koneksi gagal");
            }else{
                System.err.println("koneksi berhasil");
            }
        }catch (Exception e){
            System.err.println(""+e.getMessage());
        }
    }
    private void bacaPaket(){
        Object header[]={"No","Nama","Kuota","Kecepatan","Masa Aktif","Harga"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        tabelPaket.setModel(data);
        String sql = "select * from paket";
        try {
            getKonekPaket();
            st = paketKonek.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom3 = rs.getString(3);
                String kolom4 = rs.getString(4);
                String kolom5 = rs.getString(5);
                String kolom6 = rs.getString(6);
                String kolom[] = {kolom1, kolom2, kolom3,kolom4, kolom5, kolom6};
                data.addRow(kolom);
            }
        }catch (Exception e){
            System.err.println(e.getMessage());
        }
    }
    
    private String getTanggal() { 
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss"); 
        Date date = new Date(); 
        return dateFormat.format(date); 
    } 
    
    
    private void pilihanTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanTentangActionPerformed
        // TODO add your handling code here:
        if(pilihanTentang.getSelectedIndex() == 0){
            LCDBantuan.setText(" - Pasca bayar diperuntukkan untuk pelanggan\n"
                    + " dengan pembayaran diakhir batas waktu\n"
                    + " - Pra bayar diperuntukan untuk akses cepat dalam hal\n"
                    + " administrasi, dimana pembayaran ditujukan dalam\n"
                    + " awal pemakaian\n"
                    + " - gunakan tab daftar untuk mendaftarkan akun\n"
                    + " - gunakan field login untuk yang punya akun");
        }
        if(pilihanTentang.getSelectedIndex() == 1){
            LCDBantuan.setText("\tKami adalah sekelompok orang serbaguna "
                    + "yang mendedikasikan diri sebagai provider "
                    + "dari internet, sehingga internet bukan lagi "
                    + "merupakan barang yang sulit didapat masyarakat");
        }
        if(pilihanTentang.getSelectedIndex() == 2){
            LCDBantuan.setText("/*\n" +
                " - Purwanto            2210141039\n" +
                " - Florensius Ghesa    2210141055\n" +
                " 2 D4 TK B\n" +
                "*/");
        }
        if(pilihanTentang.getSelectedIndex() == 3){
            testimoni.show();
            String teks = testimoni.sendTestimoni();
            this.Testimoni=teks;
            LCDBantuan.setText("Testimoni anda barusan : \n"+this.Testimoni);
        }
        if(pilihanTentang.getSelectedIndex() == -1){
            LCDBantuan.setText("Silahkan pilih salah satu");
        }
    }//GEN-LAST:event_pilihanTentangActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        int kode = pra.setpraBayar();
        kodeCopyField.setText(" "+kode);
    }//GEN-LAST:event_generateButtonActionPerformed

    private void kodeCopyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeCopyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeCopyFieldActionPerformed

    private void pascaDaftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pascaDaftarButtonActionPerformed
        // TODO add your handling code here:
        String nama = pascaNamaField.getText();
        String notelp = notelpNamaField.getText();
        String email = emailNamaField.getText();
        String password = passNamaField.getText();
        if(pascaCekDaftar.isSelected()==true){
            LCDUtama.setText("Selamat datang, berikut data diri anda : \n\n"
                    + "Nama         : "+nama+"\n"
                    + "No Telp      : "+notelp+"\n"
                    + "Email        : "+email+"\n"
                    + "Password     : "+password+"\n");
            pasca.setpascaBayar(nama, notelp, email, password);
            this.pascaLogin=true;
            try {
                pasca.masukDataBase();
            } catch (SQLException ex) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception e){
                System.err.println("Gagal panggil method");
            }
        }else if(pascaCekDaftar.isSelected()==false){
            LCDUtama.setText("Maaf anda harus menyetujui terlebih "
                    + "dahulu");
        }
        pascaLogin=true;
        this.step=1;
    }//GEN-LAST:event_pascaDaftarButtonActionPerformed

    private void adminLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInButtonActionPerformed
        // TODO add your handling code here:
        String kode = adminKodeField.getText();
        String password = adminPasswordField.getText();
        if(admin.loginAdmin(kode, password) == true){
            konfirmasiAdmin.setText("! Sudah Log In");
            adminLogin = true;
            LCDUtama.setText("Selamat datang kembali\n"
                    + "mas Ghesa dan Purwanto\n"
                    + "Apa yang ingin anda inginkan?");
            tanyaAdmin.setText("silahkan pilih");
        } else {
            konfirmasiAdmin.setText("! Belum Log in");
            adminLogin = false;
        }
    }//GEN-LAST:event_adminLogInButtonActionPerformed

    private void adminLogInButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogInButton1ActionPerformed
        // TODO add your handling code here:
        if(adminLogin == false){
            LCDUtama.setText("Ubah akun gagal\n"
                    + "Silahkan log in terlebih dahulu");
        }
        if(adminLogin == true){
            if(admin.ubahAkun(ubahKode.getText(), ubahPass.getText(), konfirmasiUbah.getText()) == true){
                LCDUtama.setText("Password berhasil diubah");
            }else
            LCDUtama.setText("Ubah akun gagal\n"
                    +"coba kembali password anda");
        }
    }//GEN-LAST:event_adminLogInButton1ActionPerformed

    private void praDaftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_praDaftarButtonActionPerformed
        // TODO add your handling code here:
        pra.setKodeUser();
        if(simpanBaik2.isSelected()==true){
            LCDUtama.setText("Anda berhasil mendaftarkan diri\n"
                + "silahkan untuk memilih paket");
            this.praLogin=true;
        }else if(simpanBaik2.isSelected()==false){
            LCDUtama.setText("Harap untuk menyetujui");
        }
    }//GEN-LAST:event_praDaftarButtonActionPerformed

    private void comboPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaketActionPerformed
        // TODO add your handling code here:
        this.currentPaket = comboPaket.getSelectedIndex() + 1;
        LCDUtama.setText("Anda telah memilih paket "+this.currentPaket);
        pra.pilihPaket(currentPaket);
        pasca.pilihPaket(currentPaket);
    }//GEN-LAST:event_comboPaketActionPerformed

    private void pascaDataDiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pascaDataDiriActionPerformed
        // TODO add your handling code here:
        if((this.praLogin==true)&&(this.pascaLogin==false)){
            LCDUtama.setText("Maaf anda harus login sebagai pasca bayar");
        } else if((this.praLogin==false)&&(this.pascaLogin==true)){
             LCDUtama.setText("Berikut data diri anda : \n"
                + "Nama         : "+pasca.getNama()+"\n"
                + "No Telp      : "+pasca.getNoTelp()+"\n"
                + "Email        : "+pasca.getEmail()+"\n");
        }
    }//GEN-LAST:event_pascaDataDiriActionPerformed

    private void adminComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminComboActionPerformed
        // TODO add your handling code here:
        tampilPra tmplpra = new tampilPra();
        tampilPasca tmplpasca = new tampilPasca();
        tampilHistory his = new tampilHistory();
        if(this.adminLogin==true){
            if(adminCombo.getSelectedIndex()==0){
                LCDUtama.setText("Berikut daftar pelanggan pra bayar");//todo
                tmplpra.show();
            }
            if(adminCombo.getSelectedIndex()==1){
                LCDUtama.setText("Berikut daftar pelanggan pasca bayar");//todo
                tmplpasca.show();
            }
            if(adminCombo.getSelectedIndex()==2){
                LCDUtama.setText("Berikut list transaksi");
                his.show();
            }
        }
        else if(this.adminLogin==false)
            LCDUtama.setText("Anda bukanlah admin");
    }//GEN-LAST:event_adminComboActionPerformed

    private void beliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliButtonActionPerformed
        // TODO add your handling code here:
        if((this.praLogin==true)&&(this.pascaLogin==false)){
            //masuk history
            LCDUtama.setText("Terima kasih telah membeli\n"
                    + "Gunakan browser kami untuk menikmati paket");
            try {
                //browser.show();
                pra.masukDataBase();
            } catch (SQLException ex) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            }
            browser.enable();
        } else if((this.praLogin==false)&&(this.pascaLogin==true)){
            //todo
            try {
                pasca.masukHistory();
            } catch (SQLException ex) {
                Logger.getLogger(Utama.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception e){
                System.err.println("Gagal panggil method");
            }
            LCDUtama.setText("Terima kasih telah membeli\n"
                        + "Gunakan browser kami untuk menikmati paket");
            browser.enable();
        }
    }//GEN-LAST:event_beliButtonActionPerformed

    private void simpanBaik2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBaik2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanBaik2ActionPerformed

    private void simpanBaik2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_simpanBaik2StateChanged

    }//GEN-LAST:event_simpanBaik2StateChanged

    private void pascaCekDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pascaCekDaftarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pascaCekDaftarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.adminLogin=false;
        this.pascaLogin=false;
        this.praLogin=false;
        konfirmasiAdmin.setText("! Sudah Log out");
        LCDUtama.setText("Anda berhasil log out");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void paketBuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketBuActionPerformed
        // TODO add your handling code here:
        bacaPaket();
    }//GEN-LAST:event_paketBuActionPerformed

    private void pascaLogInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pascaLogInButtonActionPerformed
        // TODO add your handling code here:
        this.pascaLogin = pasca.loginPasca(emailField.getText(), passField.getText());
        if(pascaLogin == true){
            LCDUtama.setText("Anda telah login sebagai "+pasca.getNama());
        } else
        LCDUtama.setText("Maaf anda gagal log in");
    }//GEN-LAST:event_pascaLogInButtonActionPerformed

    private void updateJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJamActionPerformed
        // TODO add your handling code here:
        jamLabel.setText(gui.getTanggal());
    }//GEN-LAST:event_updateJamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ISP;
    private javax.swing.JTextPane LCDBantuan;
    private javax.swing.JTextPane LCDUtama;
    private javax.swing.JComboBox adminCombo;
    private javax.swing.JTextField adminKodeField;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JLabel adminLabel2;
    private javax.swing.JButton adminLogInButton;
    private javax.swing.JButton adminLogInButton1;
    private javax.swing.JTextField adminPasswordField;
    private javax.swing.JPanel adminTab;
    private javax.swing.JButton beliButton;
    private javax.swing.JComboBox comboPaket;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField emailNamaField;
    private javax.swing.JButton generateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jamLabel;
    private javax.swing.JLabel ketISP;
    private javax.swing.JTextField kodeCopyField;
    private javax.swing.JLabel konfirmasiAdmin;
    private javax.swing.JTextField konfirmasiUbah;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelInformasi;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelPass;
    private javax.swing.JLabel labelPeriintah;
    private javax.swing.JLabel labelTelp;
    private javax.swing.JTextField notelpNamaField;
    private javax.swing.JButton paketBu;
    private javax.swing.JPanel paketTab;
    private javax.swing.JCheckBox pascaCekDaftar;
    private javax.swing.JButton pascaDaftarButton;
    private javax.swing.JButton pascaDataDiri;
    private javax.swing.JButton pascaLogInButton;
    private javax.swing.JTextField pascaNamaField;
    private javax.swing.JPanel pascaTab;
    private javax.swing.JTextField passField;
    private javax.swing.JTextField passNamaField;
    private javax.swing.JComboBox pilihanTentang;
    private javax.swing.JButton praDaftarButton;
    private javax.swing.JPanel praTab;
    private javax.swing.JCheckBox simpanBaik2;
    private javax.swing.JTable tabelPaket;
    private javax.swing.JLabel tanyaAdmin;
    private javax.swing.JLabel tanyaDaftar;
    private javax.swing.JLabel tanyaDaftarPra;
    private javax.swing.JLabel tanyaLogin;
    private javax.swing.JLabel tanyaPaket;
    private javax.swing.JTextField ubahKode;
    private javax.swing.JTextField ubahPass;
    private javax.swing.JButton updateJam;
    // End of variables declaration//GEN-END:variables
}
